services:
  postgres_test:
    image: postgres:15-alpine
    container_name: pr-service-test-db
    env_file:
      - .env
    ports:
      - "${TEST_DB_PORT}:5432"
    environment:
      POSTGRES_DB: ${TEST_DB_NAME}
      POSTGRES_USER: ${TEST_DB_USER}
      POSTGRES_PASSWORD: ${TEST_DB_PASSWORD}
      DOCKER: 1
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${TEST_DB_USER} -d ${TEST_DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5