services:
  app:
    image: service:local
    container_name: pr-service-app
    ports:
    - "8080:8080" 
    depends_on:
      postgresql:
        condition: service_healthy
    environment:
      - DOCKER=1

  postgresql:
    image: postgres:18-alpine
    container_name: pr-service-psql
    ports:
    - "5432:5432"
    environment:
      - POSTGRES_DB=pr-service
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345
    healthcheck: #чтобы приложение ждало готовность БД
      test: ["CMD-SHELL", "pg_isready -U postgres -d pr-service"]
      interval: 5s
      timeout: 5s
      retries: 5