services:
  app:
    build: #будет билдиться при docker-compose up 
      context: .
      dockerfile: Dockerfile
    ports:
    - "8080:8080" 
    depends_on:
      postgresql:
        condition: service_healthy
    environment:
      - DOCKER=1

  postgresql:
    image: postgres:18-alpine
    container_name: pr-service-psql
    ports:
    - ${HOST_DB_PORT}:5432
    env_file:
      - .env
    environment: #для синхронизации .env кофига между контейнерами
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes: #сохраняем данные для следующих запусков
      - postgres_data:/var/lib/postgresql/data
    healthcheck: #чтобы приложение ждало готовность БД
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5

  postgres_test:
    image: postgres:15-alpine
    container_name: pr-service-test-db
    ports:
      - "${TEST_DB_PORT}:5432"
    environment:
      POSTGRES_DB: ${TEST_DB_NAME}
      POSTGRES_USER: ${TEST_DB_USER}
      POSTGRES_PASSWORD: ${TEST_DB_PASSWORD}
      DOCKER: 1
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${TEST_DB_USER} -d ${TEST_DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5
    
volumes:
  postgres_data: